version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: monthly
      time: '04:00'
    open-pull-requests-limit: 10
    versioning-strategy: increase
    groups:
      dependencies:
        dependency-type: 'production'
      devDependencies:
        dependency-type: 'development'
    allow:
      - dependency-name: '*'
        dependency-type: direct
  - package-ecosystem: npm
    directory: '/docs'
    schedule:
      interval: monthly
      time: '04:00'
    open-pull-requests-limit: 10
    versioning-strategy: increase
    groups:
      dependencies:
        dependency-type: 'production'
      devDependencies:
        dependency-type: 'development'
    allow:
      - dependency-name: '*'
        dependency-type: direct
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: monthly
      time: '04:00'
