name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v5
      - uses: actions/setup-node@v6
        with:
          cache: 'pnpm'
          node-version-file: '.node-version'
      - name: Install dependencies 📦
        run: pnpm install
      - name: Lint 🎨
        run: pnpm run lint
      - name: Type check 🏷
        run: pnpm run typecheck
      - name: Tests ✅
        run: pnpm run test
      - name: Upload coverage 📈
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
