name: NPM Publish
on:
  push:
    tags:
      - 'v*'
permissions:
  id-token: write
  contents: write
jobs:
  npm-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v6
      - uses: actions/setup-node@v6
        with:
          cache: 'pnpm'
          node-version-file: '.node-version'
      - name: Install dependencies 📦
        run: pnpm install
      - name: Build 👷‍♂️
        run: pnpm run build
      - name: Publish package to NPM 🚀
        run: npm publish
      - name: Get branch names 🌳
        id: branch-name
        uses: tj-actions/branch-names@v9
        with:
          strip_tag_prefix: 'v'
      - name: Publish GitHub Release 📝
        uses: softprops/action-gh-release@v2
        with:
          name: ${{steps.branch-name.outputs.tag}}
          generate_release_notes: true
